#This file was generated by VisualGDB and will be overwritten when you change the configuration via GUI.

add_definitions(-DPARAM_ASSERTIONS_ENABLED_SPI=1)
add_definitions(-DPICO_DEFAULT_SPI=spi0)
add_definitions(-DPICO_DEFAULT_SPI_SCK_PIN=6)
add_definitions(-DPICO_DEFAULT_SPI_TX_PIN=7)
add_definitions(-DPICO_DEFAULT_SPI_RX_PIN=4)
add_definitions(-DPICO_DEFAULT_SPI_CSN_PIN=5)
